name: Build Device Tree Overlays

on:
  push:
    paths:
      - 'rpi/display/**'
  pull_request:
    paths:
      - 'rpi/display/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y device-tree-compiler gcc make git

      - name: Build overlays
        run: |
          cd rpi/display
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dtbo-overlays
          path: rpi/display/*.dtbo
