name: Utility Touch

on:
  workflow_call:
  push:
    paths:
      - 'rpi/touch/**'
  pull_request:
    paths:
      - 'rpi/touch/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu libc6-dev-armhf-cross libc6-dev-arm64-cross make

      - name: Build 32-bit
        run: |
          cd rpi/touch
          make 32

      - name: Build 64-bit
        run: |
          cd rpi/touch
          make 64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: touch
          path: |
            rpi/touch/32
            rpi/touch/64
